# Generated by Django 2.0.2 on 2018-05-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=40)),
                ('course_city', models.CharField(max_length=20)),
                ('course_state', models.CharField(max_length=2)),
                ('hole01_par', models.PositiveSmallIntegerField()),
                ('hole02_par', models.PositiveSmallIntegerField()),
                ('hole03_par', models.PositiveSmallIntegerField()),
                ('hole04_par', models.PositiveSmallIntegerField()),
                ('hole05_par', models.PositiveSmallIntegerField()),
                ('hole06_par', models.PositiveSmallIntegerField()),
                ('hole07_par', models.PositiveSmallIntegerField()),
                ('hole08_par', models.PositiveSmallIntegerField()),
                ('hole09_par', models.PositiveSmallIntegerField()),
                ('hole10_par', models.PositiveSmallIntegerField()),
                ('hole11_par', models.PositiveSmallIntegerField()),
                ('hole12_par', models.PositiveSmallIntegerField()),
                ('hole13_par', models.PositiveSmallIntegerField()),
                ('hole14_par', models.PositiveSmallIntegerField()),
                ('hole15_par', models.PositiveSmallIntegerField()),
                ('hole16_par', models.PositiveSmallIntegerField()),
                ('hole17_par', models.PositiveSmallIntegerField()),
                ('hole18_par', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
