# Generated by Django 2.0.2 on 2018-05-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20180520_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isgolfing',
            field=models.BooleanField(default=True),
        ),
    ]
