# Generated by Django 2.0.2 on 2018-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0004_user_isgolfing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='handicap',
            new_name='r1_netscore',
        ),
        migrations.AddField(
            model_name='user',
            name='r1_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r1_quota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r1_rawscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r2_group',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r2_netscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r2_quota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r2_rawscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r2_startscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r3_group',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r3_netscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r3_quota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r3_rawscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='r3_startscore',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
