# Generated by Django 2.0.2 on 2018-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0005_auto_20180526_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='r2_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='r3_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
        ),
    ]
