# Generated by Django 2.0.2 on 2018-05-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0008_auto_20180526_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isgolfing',
            field=models.BooleanField(default=True),
        ),
    ]
