# Generated by Django 2.0.2 on 2018-05-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0010_auto_20180526_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveSmallIntegerField(default=0)),
                ('display_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('city', models.CharField(default='City', max_length=20)),
                ('state', models.CharField(default='FL', max_length=2)),
                ('isgolfing', models.NullBooleanField(default=True)),
                ('r1_quota', models.PositiveSmallIntegerField(default=0)),
                ('r1_group', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('r1_rawscore', models.SmallIntegerField(default=0)),
                ('r1_netscore', models.SmallIntegerField(default=0)),
                ('r2_quota', models.PositiveSmallIntegerField(default=0)),
                ('r2_group', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('r2_startscore', models.SmallIntegerField(default=0)),
                ('r2_rawscore', models.SmallIntegerField(default=0)),
                ('r2_netscore', models.SmallIntegerField(default=0)),
                ('r3_quota', models.PositiveSmallIntegerField(default=0)),
                ('r3_group', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('r3_startscore', models.SmallIntegerField(default=0)),
                ('r3_rawscore', models.SmallIntegerField(default=0)),
                ('r3_netscore', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
