# Generated by Django 2.0.2 on 2018-05-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0011_auto_20180527_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
