# Generated by Django 2.0.2 on 2018-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0012_auto_20180527_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
