# Generated by Django 2.0.2 on 2018-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0014_auto_20180604_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundData',
        ),
    ]
