# Generated by Django 2.0.2 on 2018-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0015_delete_rounddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('group1_ttime', models.TimeField()),
                ('group2_ttime', models.TimeField()),
                ('group3_ttime', models.TimeField()),
                ('group4_ttime', models.TimeField()),
                ('group5_ttime', models.TimeField()),
            ],
        ),
    ]
