# Generated by Django 2.0.6 on 2018-06-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0016_rounddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='display_name',
        ),
        migrations.AddField(
            model_name='daily',
            name='golfer',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h10_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h11_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h12_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h13_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h14_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h15_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h16_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h17_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h18_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h1_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h2_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h3_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h4_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h5_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h6_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h7_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h8_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h9_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('aweful', 0), ('bogey', 1), ('par', 2), ('birdy', 4), ('eagle', 8), ('d_eagle', 10)], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='net_day_points',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='net_tourney_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='raw_day_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
