# Generated by Django 2.0.6 on 2018-06-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0017_auto_20180615_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=200, null=True)),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r1_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r2_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r3_group',
        ),
        migrations.AddField(
            model_name='daily',
            name='startscore',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='teetime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='thru',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='user_name',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='r1_startscore',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='golfer',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
