# Generated by Django 2.0.6 on 2018-06-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0019_auto_20180619_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
