# Generated by Django 2.0.6 on 2018-06-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0020_auto_20180620_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='hole01_par',
            new_name='h10_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole02_par',
            new_name='h11_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole03_par',
            new_name='h12_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole04_par',
            new_name='h13_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole05_par',
            new_name='h14_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole06_par',
            new_name='h15_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole07_par',
            new_name='h16_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole08_par',
            new_name='h17_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole09_par',
            new_name='h18_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole10_par',
            new_name='h1_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole11_par',
            new_name='h2_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole12_par',
            new_name='h3_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole13_par',
            new_name='h4_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole14_par',
            new_name='h5_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole15_par',
            new_name='h6_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole16_par',
            new_name='h7_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole17_par',
            new_name='h8_par',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hole18_par',
            new_name='h9_par',
        ),
        migrations.RenameField(
            model_name='rounddata',
            old_name='current_round',
            new_name='round',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_city',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_state',
        ),
        migrations.AddField(
            model_name='profile',
            name='r1_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='r2_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='r3_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='rounddata',
            name='course',
            field=models.CharField(default='Palmer', max_length=40),
            preserve_default=False,
        ),
    ]
