# Generated by Django 2.0.6 on 2018-06-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0021_auto_20180620_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='user_name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
