# Generated by Django 2.0.6 on 2018-06-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0022_auto_20180620_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='h15_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Aweful'), (1, 'Bogey'), (2, 'Par'), (4, 'Birdie'), (8, 'Eagle'), (10, 'D_Eagle')], null=True),
        ),
    ]
