# Generated by Django 2.0.6 on 2018-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0024_auto_20180621_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='h10_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h11_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h12_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h13_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h14_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h15_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h16_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h17_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h18_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h1_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h2_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h3_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h4_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h5_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h6_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h7_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h8_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='h9_pts',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (10, '10')], null=True),
        ),
    ]
