# Generated by Django 2.0.6 on 2018-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0025_auto_20180623_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundData',
        ),
        migrations.AddField(
            model_name='daily',
            name='course',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='r1_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daily',
            name='r2_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Nicklaus', 'Nicklaus'), ('Palmer', 'Palmer')], max_length=30),
        ),
    ]
