# Generated by Django 2.0.6 on 2018-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0026_auto_20180624_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='startscore',
        ),
        migrations.AddField(
            model_name='profile',
            name='r4_quota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
