# Generated by Django 2.0.6 on 2018-06-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0027_auto_20180624_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='r1_netscore',
            new_name='r1_score',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='r1_rawscore',
            new_name='r2_score',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='r1_startscore',
            new_name='r3_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r2_netscore',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r2_rawscore',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r2_startscore',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r3_netscore',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r3_rawscore',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='r3_startscore',
        ),
    ]
