# Generated by Django 2.0.6 on 2018-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0028_auto_20180624_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='r4_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
