# Generated by Django 2.2.3 on 2020-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0029_profile_r4_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Nicklaus', 'Nicklaus'), ('Palmer', 'Palmer'), ('Copperhead (white)', 'Copperhead (white)'), ('Island (white)', 'Island (white)'), ('North (white)', 'North (white)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='daily',
            name='grouping',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r1_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r2_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r3_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r4_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
    ]
