# Generated by Django 2.2.3 on 2020-05-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0030_auto_20200525_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TextField(null=True)),
                ('rules', models.TextField(null=True)),
                ('payouts', models.TextField(null=True)),
                ('courses', models.TextField(null=True)),
            ],
        ),
    ]
