# Generated by Django 2.2.3 on 2020-05-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0031_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Tourneyinfo',
        ),
    ]
