# Generated by Django 2.2.3 on 2020-05-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0032_auto_20200527_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tourneyinfo',
        ),
    ]
