# Generated by Django 2.2.3 on 2020-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0035_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='leader',
            field=models.CharField(blank=True, default=None, max_length=30),
            preserve_default=False,
        ),
    ]
