# Generated by Django 2.2.3 on 2020-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0036_auto_20200530_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='hole',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], null=True, unique=True),
        ),
    ]
