# Generated by Django 2.2.3 on 2020-06-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0037_auto_20200530_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0),
        ),
    ]
