# Generated by Django 4.0.4 on 2022-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0038_auto_20200612_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Nicklaus', 'Nicklaus'), ('Palmer', 'Palmer'), ('Copperhead (white)', 'Copperhead (white)'), ('Island (white)', 'Island (white)'), ('North (white)', 'North (white)'), ('Ocean', 'Ocean'), ('Conservatory', 'Conservatory'), ('Las Colinas', 'Las Colinas'), ('El Campeon', 'El Campeon')], max_length=30),
        ),
        migrations.AlterField(
            model_name='daily',
            name='grouping',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='daily',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='isgolfing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r1_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r2_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r3_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='r4_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0),
        ),
    ]
