# Generated by Django 4.0.4 on 2022-09-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0040_alter_course_id_alter_daily_id_alter_extra_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=15)),
                ('time', models.DateField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
                ('zoneRoof', models.CharField(max_length=200)),
                ('zonePalms', models.CharField(max_length=200)),
            ],
        ),
    ]
