# Generated by Django 4.0.4 on 2022-09-13 01:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0042_alter_lights_zonepalms_alter_lights_zoneroof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lights',
            name='zonePalms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lights',
            name='zoneRoof',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple')], max_length=50),
        ),
    ]
