# Generated by Django 4.0.4 on 2022-09-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0043_alter_lights_zonepalms_alter_lights_zoneroof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lights',
            name='zoneRoof',
            field=models.CharField(choices=[('White', 'White'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple')], max_length=50),
        ),
    ]
