# Generated by Django 4.0.4 on 2022-09-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0044_alter_lights_zoneroof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lights',
            name='zoneRoof',
            field=models.CharField(max_length=50),
        ),
    ]
