# Generated by Django 4.0.4 on 2022-09-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0045_alter_lights_zoneroof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=15)),
                ('time', models.DateField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LightColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
                ('hsv', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Lights',
        ),
    ]
