# Generated by Django 4.0.4 on 2022-09-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0046_light_lightcolor_delete_lights'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='zonePalms',
            field=models.ManyToManyField(related_name='zonePalmsColor', to='tourney.lightcolor'),
        ),
        migrations.AddField(
            model_name='light',
            name='zoneRoof',
            field=models.ManyToManyField(related_name='zoneRoofColor', to='tourney.lightcolor'),
        ),
    ]
