# Generated by Django 4.0.4 on 2022-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0047_light_zonepalms_light_zoneroof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='zonePalms',
        ),
        migrations.AddField(
            model_name='light',
            name='zonePalms',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.RemoveField(
            model_name='light',
            name='zoneRoof',
        ),
        migrations.AddField(
            model_name='light',
            name='zoneRoof',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.DeleteModel(
            name='LightColor',
        ),
    ]
