# Generated by Django 4.0.4 on 2022-09-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0048_remove_light_zonepalms_light_zonepalms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='zonePalms',
            new_name='PalmColors',
        ),
        migrations.RenameField(
            model_name='light',
            old_name='zoneRoof',
            new_name='RoofColors',
        ),
        migrations.AddField(
            model_name='light',
            name='PalmEffect',
            field=models.CharField(default='Solid', max_length=15),
        ),
        migrations.AddField(
            model_name='light',
            name='RoofEffect',
            field=models.CharField(default='Solid', max_length=15),
        ),
    ]
