# Generated by Django 4.0.4 on 2022-09-15 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0049_rename_zonepalms_light_palmcolors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='time',
        ),
        migrations.AddField(
            model_name='light',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
