# Generated by Django 4.0.4 on 2022-09-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0050_remove_light_time_light_timecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='timeCreated',
            new_name='postTime',
        ),
    ]
