# Generated by Django 4.0.4 on 2022-09-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0051_rename_timecreated_light_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light',
            name='PalmColors',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AlterField(
            model_name='light',
            name='RoofColors',
            field=models.CharField(default='White', max_length=100),
        ),
    ]
