# Generated by Django 4.0.4 on 2022-10-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0052_alter_light_palmcolors_alter_light_roofcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='FloodColors',
            field=models.CharField(default='White', max_length=25),
        ),
        migrations.AddField(
            model_name='light',
            name='SconceColors',
            field=models.CharField(default='White', max_length=25),
        ),
    ]
