# Generated by Django 4.0.4 on 2022-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0053_light_floodcolors_light_sconcecolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='GarageFrameColors',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AddField(
            model_name='light',
            name='SnowFlakeColors',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AddField(
            model_name='light',
            name='StripePalmColor',
            field=models.CharField(default='Red', max_length=25),
        ),
    ]
