# Generated by Django 4.0.4 on 2023-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0054_light_garageframecolors_light_snowflakecolors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('Nicklaus', 'Nicklaus'), ('Palmer', 'Palmer'), ('Copperhead (white)', 'Copperhead (white)'), ('Island (white)', 'Island (white)'), ('North (white)', 'North (white)'), ('Ocean', 'Ocean'), ('Conservatory', 'Conservatory'), ('Las Colinas', 'Las Colinas'), ('El Campeon', 'El Campeon'), ('International', 'International')], max_length=30),
        ),
    ]
