# Generated by Django 4.0.4 on 2023-05-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0055_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='team',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30),
        ),
    ]
