# Generated by Django 4.0.4 on 2023-06-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0056_alter_daily_team_alter_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='roomTeam',
            field=models.CharField(choices=[('Chili Dippers', 'Chili Dippers'), ('Douche Bags', 'Douche Bags'), ('Three and a Half Men', 'Three and a Half Men'), ('The ASStronauts', 'The ASStronauts'), ('Piss Missiles', 'Piss Missiles'), ('Fireball', 'Fireball'), ('Tee Baggers', 'Tee Baggers')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='roomTeam',
            field=models.CharField(choices=[('Chili Dippers', 'Chili Dippers'), ('Douche Bags', 'Douche Bags'), ('Three and a Half Men', 'Three and a Half Men'), ('The ASStronauts', 'The ASStronauts'), ('Piss Missiles', 'Piss Missiles'), ('Fireball', 'Fireball'), ('Tee Baggers', 'Tee Baggers')], max_length=30, null=True),
        ),
    ]
