# Generated by Django 4.0.4 on 2023-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0057_daily_roomteam_profile_roomteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roomTeam',
            field=models.CharField(blank=True, choices=[('Chili Dippers', 'Chili Dippers'), ('Douche Bags', 'Douche Bags'), ('Three and a Half Men', 'Three and a Half Men'), ('The ASStronauts', 'The ASStronauts'), ('Piss Missiles', 'Piss Missiles'), ('Fireball', 'Fireball'), ('Tee Baggers', 'Tee Baggers')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=30),
        ),
    ]
